service: serverless-todo-app

plugins:
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb
  - serverless-s3-local
  - serverless-webpack

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  tracing:
    apiGateway: true
    lambda: true
  environment:
    S3_BUCKET_NAME: son-doong-bucket
    SIGNED_URL_EXPIRATION: 300
    TODO_TABLE: SonDoongable
    USER_ID_INDEX: SonDoongUserIdIndex
    JWKS_URL: https://dev-ubzav6t2jjro4wgw.us.auth0.com/.well-known/jwks.json

custom:
  documentation:
    api:
      info:
        version: "1.0"
        title: Son Doong Lambda App
        description: Son Doong Lambda app demo
      tags:
        - name: sodo
          description: sodo items
  serverless-offline:
    httpPort: 5000
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      docker: true
  s3:
    host: localhost
    port: 4569
    directory: ./sodo-bucket/

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos

  # TODO: Configure this function
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos

  # TODO: Configure this function
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}

  # TODO: Configure this function
  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}

  # TODO: Configure this function
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment

resources:
  Resources:
    # TODO: Add any necessary AWS resources